test pull docker actions

diff --git a/.github/workflows/control_tests.yaml b/.github/workflows/control_tests.yaml
--- a/.github/workflows/control_tests.yaml
+++ b/.github/workflows/control_tests.yaml
@@ -29,24 +29,54 @@ jobs:
         echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > kaggle.json
         chmod 400 kaggle.json
 
-    # - name: Set up QEMU
-    #   uses: docker/setup-qemu-action@v2
 
-    # - name: Login to DockerHub
-    #   uses: docker/login-action@v2
-    #   with:
-    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
-    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    # - name: Set up Docker Buildx
-    #   uses: docker/setup-buildx-action@v3
-      
-    # - name: Build and push Docker images
-    #   run: |
-    #     cd docker
-    #     docker compose config
-    #     docker compose build
-    #     docker compose push
+
+
+
+
+
+
+
+
+    - name: Login to DockerHub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+
+    - name: Define Docker image tags
+      id: set-tags
+      run: |
+        echo "DOCKER_IMAGES=user_api admin_api inference training preprocessing monitoring mlflowui streamlit" >> $GITHUB_ENV
+
+    - name: Pull Docker images
+      run: |
+        for docker_image in $DOCKER_IMAGES; do
+          echo "Pulling ruizguillaume/aviscan:${docker_image}"
+          docker pull ruizguillaume/aviscan:${docker_image}
+          if [ "$(docker images -q ruizguillaume/aviscan:${docker_image} 2> /dev/null)" == "" ]; then
+            echo "Docker image ruizguillaume/aviscan:${docker_image} not found!"
+            exit 1
+          else
+            echo "Docker image ruizguillaume/aviscan:${docker_image} pulled successfully!"
+          fi
+        done
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
     - name: Run unit tests
       run: |
